
name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t directorio-cuantico .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name directorio_cuantico directorio-cuantico
