name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 1'  # Corre cada lunes a medianoche
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Analizar dependencias con Dependabot
        uses: github/codeql-action/analyze
